name: Update Future Games

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:  # Tämä mahdollistaa manuaalisen käynnistyksen

jobs:
  update-games:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Update future games
        run: python update_games.py

      - name: Commit and push if changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add -A
          git commit -m "Updated future games" || exit 0  # Exit 0 if no changes
          git push

