name: Päivittäinen Yleisölaskuri

on:
  schedule:
    # Asetetaan suoritusajankohta joka päivä klo 22:00 UTC
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  calculate_audience:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Varmista, että tämä versio sopii koodillesi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Yleisölaskuri script
      run: python Veikkausliiga/scripts/Yleisölaskuri.py

    - name: Commit and push if changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add Veikkausliiga2024/Yleisö2024.md
        git commit -m "Update audience counts" || echo "No changes to commit"
        git push
